Events/Models/AddEvents.cs
using System.ComponentModel.DataAnnotations;

namespace Events.Models
{
    public class AddEvents
    {
        public int Id { get; set; }
        [StringLength(64, MinimumLength = 3)]
        [Required]
        [Display(Name = "Ürituse nimi")]
        public string Nimi { get; set; }
        [Required(ErrorMessage = "Palun sisesta kuupäev, formaat: pp.kk.aaaa hh:mm")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy hh:mm}")]
        public DateTime Toimumisaeg { get; set; }
        [StringLength(64)]
        [Required]
        public string Koht { get; set; }
        [StringLength(1000)]
        public string? Lisainfo { get; set; }
    }
}

Events/Models/ErrorViewModel.cs
namespace Events.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Events/Models/EventsDetailsViewModel.cs
namespace Events.Models
{
    public class EventsDetailsViewModel
    {
        public AddEvents? Events { get; set; }
        public List<PrivateParticipants>? privateParticipants { get; set; }
        public List<CompanyParticipants>? companyParticipants { get; set; }
        public int EventsId { get; set; }
        public PrivateParticipants? privateParticipantsModel { get; set; }
        public CompanyParticipants? companyParticipantsModel { get; set; }
    }
}

Events/Models/ParticipantsModel.cs
using System.ComponentModel.DataAnnotations;

namespace Events.Models
{
    public class PrivateParticipants
    {
        [Key]
        public int PrivateId { get; set; }
        [StringLength(64, MinimumLength = 3)]
        [Required]
        public string Eesnimi { get; set; }
        [Required]
        public string Perekonnanimi { get; set; }
        [Required]
        public int Isikukood { get; set; }
        [Required]
        public string Maksmisviis { get; set; }
        [StringLength(1500)]
        public string? Lisainfo { get; set; }
        public virtual AddEvents? Events { get; set; }
    }

    public class CompanyParticipants
    {
        [Key]
        public int CompanyId { get; set; }
        [StringLength(64, MinimumLength = 3)]
        [Required]
        [Display(Name = "Juriidiline nimi")]
        public string Nimi { get; set; }
        [Required]
        public int Registrikood { get; set; }
        [Required]
        [Display(Name = "Osavõtjate arv")]
        public int Osavõtjate_arv { get; set; }
        [Required]
        public string Maksmiseviis { get; set; }
        [StringLength(5000)]
        public string? Lisainfo { get; set; }
        public virtual AddEvents? Events { get; set; }
    }
}

Events/Controllers/AddEventsController.cs
using Events.Data;
using Events.Models;
using Microsoft.AspNetCore.Mvc;

namespace Events.Controllers
{
    public class AddEventsController : Controller
    {
        private readonly EventsContext _context;

        public AddEventsController(EventsContext context)
        {
            _context = context;
        }

        // GET: AddEvents
        public IActionResult Index()
        {
            // Create Page
            return View();
        }

        // POST: AddEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nimi,Toimumisaeg,Koht,Lisainfo")] AddEvents addEvents)
        {
            if (ModelState.IsValid)
            {
                _context.Add(addEvents);
                await _context.SaveChangesAsync();
                // return RedirectToAction(nameof(Index));
                return LocalRedirect("~/");
            }
            return View(addEvents);
        }
    }
}

Events/Controllers/HomeController.cs
using Events.Data;
using Events.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Events.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly EventsContext _context;

        public HomeController(EventsContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return _context.AddEvents != null ?
                          View(await _context.AddEvents.ToListAsync()) :
                          Problem("Entity set 'EventsContext.AddEvents'  is null.");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AddEvents == null)
            {
                return Problem("Entity set 'EventsContext.AddEvents'  is null.");
            }
            var addEvents = await _context.AddEvents.FindAsync(id);
            if (addEvents != null)
            {
                _context.AddEvents.Remove(addEvents);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Events/Views/AddEvents/Create.cshtml
@model IEnumerable<Events.Models.AddEvents>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nimi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Toimumisaeg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Koht)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lisainfo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nimi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Toimumisaeg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Koht)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lisainfo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}

        @section Scripts {
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }
    </tbody>
</table>

Events/Views/AddEvents/Index.cshtml
@model Events.Models.AddEvents

@{
    ViewData["Title"] = "Ürituse lisamine";
}

<!-- HERO HEADER -->
<partial name="_TinyHeaderPartial" />

<!-- HERO -->
<div class="bg-white mb-4">
    <div class="col-xl-5 mx-auto p-4">
        <form asp-action="Create" class="mb-4">
            <h4 style="color: var(--bg);">@ViewData["Title"]</h4>
            <div class="form-group row p-1">
                <label asp-for="Nimi" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Nimi):</label>
                <div class="col-sm-8">
                    <input asp-for="Nimi" class="form-control" />
                    <span asp-validation-for="Nimi" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row p-1">
                <label asp-for="Toimumisaeg" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Toimumisaeg):</label>
                <div class="col-sm-8">
                    <input asp-for="Toimumisaeg" class="form-control bg-white datetimepicker" type="datetime" placeholder="pp.kk.aaaa hh:mm" autocomplete="off" readonly/>
                    <span asp-validation-for="Toimumisaeg" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row p-1">
                <label asp-for="Koht" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Koht):</label>
                <div class="col-sm-8">
                    <input asp-for="Koht" class="form-control" />
                    <span asp-validation-for="Koht" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row p-1">
                <label asp-for="Lisainfo" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Lisainfo):</label>
                <div class="col-sm-8">
                    <textarea asp-for="Lisainfo" class="form-control"></textarea>
                    <span asp-validation-for="Lisainfo" class="text-danger"></span>
                </div>
            </div>
            <div class="mt-5">
                <a onclick="history.back()" class="btn py-1 m-1" style="background-color: #e1e1e1;">Tagasi</a>
                <input type="submit" value="Salvesta" class="btn text-white py-1 m-1" style="background-color: var(--bg);" />
            </div>
        </form>
    </div>
</div>

<link href="~/lib/jquery-datetimepicker/jquery.datetimepicker.css" rel="stylesheet" />
<link href="~/lib/jquery-datetimepicker/jquery.datetimepicker.min.css" rel="stylesheet" />

@section Scripts {

    <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.full.js"></script>
    <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.full.min.js"></script>
    <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.js"></script>
    <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.min.js"></script>

    <script>

        $(function () {
          $(".datetimepicker").datetimepicker({
              format: "d.m.Y H:i",
              theme: 'dark'
            });
        });

    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Events/Views/Home/Index.cshtml
@model IEnumerable<Events.Models.AddEvents>

@{
    int i = 1;

    ViewData["Title"] = "Avaleht";
}

<!-- HERO 1 -->
<div class="row g-0">
    <div class="col bg py-5">
        <h4 class="p-5 text-center text-white">
            Sed nec elit vestibulum, <b>tincidunt orci</b> et, sagittis ex.
            Vestibulum rutrum <b>neque suscipit</b> ante mattis maximus. Nulla non sapien <b>viverra, lobortis lorem non,</b> accumsan metus.
        </h4>
    </div>
    <div class="col">
        <img src="~/img/pilt.jpg" class="w-100 h-100" alt="Pilt">
    </div>
</div>

<!-- HERO 2 -->
<div class="row g-0 py-4">
    <div class="col me-3 bg-white">
        <h4 class="bg py-3 text-center text-white">Tulevased üritused</h4>
        @foreach (var item in Model.OrderBy(item => item.Toimumisaeg))
        {
            @if (item.Toimumisaeg > DateTime.Now)
            {
                <small>
                    <div class="row g-0 px-4">
                        <div class="col p-1">
                            @(i++). @Html.DisplayFor(modelItem => item.Nimi)
                        </div>
                        <div class="col col-lg-2 p-1 d-flex align-items-start justify-content-center">
                            @item.Toimumisaeg.ToString("dd.MM.yyyy")
                        </div>

                        <form class="col col-lg-3 p-1 d-flex align-items-start justify-content-end" asp-route-id="@item.Id" asp-action="Delete" method="post">
                            <a asp-action="Details" asp-controller="Participants" asp-route-id="@item.Id" class="text-decoration-none opacity-50 text-uppercase text-dark fw-bold">Osavõtjad</a>
                            <input type="image" src="../Img/remove.svg" width="24" height="24" asp-for="@item.Id" class="ps-2 opacity-50" />
                        </form>
                    </div>
                </small>
            }
        }

        @foreach (var item in Model)
        {
            @if (DateTime.Now > item.Toimumisaeg)
            {
                <div class="p-3"></div>
            }
        }

        <div class="p-3">
            <a class="text-uppercase text-dark fw-bold opacity-50 text-decoration-none" asp-controller="AddEvents" asp-action="Index">Lisa üritus</a>
        </div>

    </div>


    @{
        i = 1;
    }
    <div class="col ms-3 bg-white">
        <h4 class="bg py-3 text-center text-white">Toimunud üritused</h4>
        @foreach (var item in Model.OrderByDescending(item => item.Toimumisaeg))
        {
            @if (DateTime.Now > item.Toimumisaeg)
            {
                <small>
                    <div class="row g-0 px-4">
                        <div class="col p-1">
                            @(i++). @Html.DisplayFor(modelItem => item.Nimi)
                        </div>
                        <div class="col col-lg-2 p-1 d-flex align-items-start justify-content-center">
                            @item.Toimumisaeg.ToString("dd.MM.yyyy")
                        </div>
                        <div class="col col-lg-3 p-1 d-flex align-items-start justify-content-end opacity-50">
                            <a class="text-decoration-none text-uppercase text-dark fw-bold" asp-action="Details" asp-controller="Participants" asp-route-id="@item.Id">Osavõtjad</a>
                        </div>
                    </div>
                </small>
            }
        }
    </div>
</div>

Events/Views/Participants/CompanyParticipant.cshtml
@model Events.Models.EventsDetailsViewModel
@{
    ViewData["Title"] = "Osavõtja info";
}

<!-- HERO HEADER -->
<partial name="_TinyHeaderPartial" />

<!-- HERO -->
<div class="bg-white mb-4">
    <div class="col-xl-5 mx-auto p-4">
        <!-- FORM ACTION? -->
        <form class="mb-4" asp-action="CompanyParticipant">
            <h4 style="color: var(--bg);">@ViewData["Title"]</h4>
            <partial name="_CompanyParticipantsPartial" model="Model" />
        </form>
    </div>
</div>

Events/Views/Participants/Details.cshtml
@model Events.Models.EventsDetailsViewModel

@{
    int counter = 1;

    ViewData["Title"] = "Osavõtjad";
}

<!-- HERO HEADER -->
<partial name="_TinyHeaderPartial" />

<!-- HERO -->
<div class="bg-white mb-4">
    <div class="col-xl-5 mx-auto p-4">
        <h4 style="color: var(--bg);">@ViewData["Title"]</h4>
        <div class="row p-1 g-0">
            <div class="form-group row p-1">
                <h4 class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Events.Nimi):</h4>
                <div class="col-sm-8 col-form-label">@Html.DisplayFor(model => model.Events.Nimi)</div>
            </div>
            <div class="form-group row p-1">
                <h4 class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Events.Toimumisaeg):</h4>
                <div class="col-sm-8 col-form-label">@Model.Events.Toimumisaeg.ToString("dd.MM.yyyy")</div>
            </div>
            <div class="form-group row p-1">
                <h4 class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.Events.Koht):</h4>
                <div class="col-sm-8 col-form-label">@Html.DisplayFor(model => model.Events.Koht)</div>
            </div>
            <div class="form-group row p-1">
                <h4 class="col-lg-4 col-form-label">@ViewData["Title"]:</h4>
            </div>
        </div>
    </div>

    @for (var i = 0; i < Model.privateParticipants.Count(); i++)
    {
        <small>
            <div class="row g-0 p-1 col-sm-8 ms-auto">
                <div class="col-sm-4 py-1 px-3">
                    @(counter++). @Html.DisplayFor(modelItem => modelItem.privateParticipants[i].Eesnimi)
                </div>
                <div class="col-sm-3 py-1 px-3">
                    @Html.DisplayFor(modelItem => modelItem.privateParticipants[i].Isikukood)
                </div>
                <div class="col-sm-4 py-1 opacity-50 px-3">
                    <form asp-route-id="@Model.privateParticipants[i].PrivateId" asp-route-eventsId="@Model.privateParticipants[i].Events.Id" asp-action="DeletePrivateParticipant" method="post">
                        <a class="px-3 text-decoration-none text-uppercase text-dark fw-bold" asp-route-id="@Model.privateParticipants[i].PrivateId" asp-route-eventsId="@Model.privateParticipants[i].Events.Id" asp-action="PrivateParticipant">Vaata</a>
                        <a href="javascript:{}" onclick="this.closest('form').submit(); return false;" class="px-3 text-decoration-none text-uppercase text-dark fw-bold">Kustuta</a>
                    </form>
                </div>
            </div>
        </small>
    }

    @for (var i = 0; i < Model.companyParticipants.Count(); i++)
    {
        <small>
            <div class="row g-0 p-1 col-sm-8 ms-auto">
                <div class="col-sm-4 py-1 px-3">
                    @(counter++). @Html.DisplayFor(modelItem => modelItem.companyParticipants[i].Nimi)
                </div>
                <div class="col-sm-3 py-1 px-3">
                    @Html.DisplayFor(modelItem => modelItem.companyParticipants[i].Registrikood)
                </div>
                <div class="col-sm-4 py-1 opacity-50 px-3">
                    <form asp-route-id="@Model.companyParticipants[i].CompanyId" asp-route-eventsId="@Model.companyParticipants[i].Events.Id" asp-action="DeleteCompanyParticipant" method="post">
                        <a class="px-3 text-decoration-none text-uppercase text-dark fw-bold" asp-route-id="@Model.companyParticipants[i].CompanyId" asp-route-eventsId="@Model.companyParticipants[i].Events.Id" asp-action="CompanyParticipant">Vaata</a>
                        <a href="javascript:{}" onclick="this.closest('form').submit(); return false;" class="px-3 text-decoration-none text-uppercase text-dark fw-bold">Kustuta</a>
                    </form>
                </div>
            </div>
        </small>
    }

    <div class="col-xl-5 mx-auto p-4">
        <h4 style="color: var(--bg);">Osavõtjate lisamine</h4>
        <div class="form-group row p-1">
            <div class="col-lg-4 col-form-label"></div>
            <div class="col-sm-8 px-3 py-1">
                <div class="form-check form-check-inline pe-5">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="eraisik" onclick="checkRadio()">
                    <label class="form-check-label" for="inlineRadio1">Eraisik</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="juriidiline" onclick="checkRadio()">
                    <label class="form-check-label" for="inlineRadio2">Ettevõte</label>
                </div>
            </div>
        </div>

        <div id="eraisik" style="display:none;">
            <form action="@Url.Action("CreatePrivateParticipant")" method="post">
                <partial name="_PrivateParticipantsPartial" model="Model" />
            </form>
        </div>

        <div id="juriidiline" style="display:none;">
            <form action="@Url.Action("CreateCompanyParticipant")" method="post">
                <partial name="_CompanyParticipantsPartial" model="Model" />
            </form>
        </div>

    </div>
</div>

<!-- SCRIPTS FOR THIS PAGE -->
<script>

    if (localStorage.getItem("juriidiline")) {
        document.querySelector('#inlineRadio2').checked = true;
        document.getElementById("eraisik").style.display = "none";
        document.getElementById("juriidiline").style.display = "initial";
    } else {
        document.querySelector('#inlineRadio1').checked = true;
        document.getElementById("juriidiline").style.display = "none";
        document.getElementById("eraisik").style.display = "initial";
    }

</script>

Events/Views/Participants/Info.cshtml
@model Events.Models.EventsDetailsViewModel
@{
    ViewData["Title"] = "Osavõtja info";
}

<!-- HERO HEADER -->
<partial name="_TinyHeaderPartial" />

<!-- HERO -->
<div class="bg-white mb-4">
    <div class="p-4 d-flex align-items-center justify-content-center">
        <!-- FORM ACTION? -->
        <form class="mb-4">
            <h4 style="color: var(--bg);">Osavõtja info</h4>
            <div class="form-group row p-1">
                <label for="inputNimi" class="col-lg-4 col-form-label">Eesnimi:</label>
                <div class="col-sm-8">
                    <input type="nimi" class="form-control" id="inputNimi" value="Model.Eesnimi">
                </div>
            </div>
            <div class="form-group row p-1">
                <label for="inputAeg" class="col-lg-4 col-form-label">Perenimi:</label>
                <div class="col-sm-8">
                    <input type="aeg" class="form-control" id="inputAeg" value="Model.Perekonnanimi">
                </div>
            </div>
            <div class="form-group row p-1">
                <label for="inputKoht" class="col-lg-4 col-form-label">Isikukood:</label>
                <div class="col-sm-8">
                    <input type="koht" class="form-control" id="inputKoht" value="Model.Isikukood">
                </div>
            </div>
            <div class="form-group row p-1">
                <label for="FormSelect" class="col-lg-4 col-form-label">Maksmisviis:</label>
                <div class="col-sm-8">
                    <select type="maksmisviis" class="form-select" id="FormSelect">
                        <option>Sularaha</option>
                        <option>Pangaülekanne</option>
                    </select>
                </div>
            </div>
            <div class="form-group row p-1">
                <label for="inputInfo" class="col-lg-4 col-form-label">Lisainfo:</label>
                <div class="col-sm-8">
                    <textarea class="form-control" id="inputInfo" type="info" rows="3" value="Model.Private_Lisainfo"></textarea> <!-- here goes with at too to read the value -->
                </div>
            </div>
            <div class="mt-5">
                <a onclick="history.back()" class="btn py-1 m-1" style="background-color: #e1e1e1;">Tagasi</a>
                <button type="submit" class="btn text-white py-1 m-1" style="background-color: var(--bg);">Salvesta</button>
            </div>
        </form>
    </div>
</div>

Events/Views/Participants/PrivateParticipant.cshtml
@model Events.Models.EventsDetailsViewModel
@{
    ViewData["Title"] = "Osavõtja info";
}

<!-- HERO HEADER -->
<partial name="_TinyHeaderPartial" />

<!-- HERO -->
<div class="bg-white mb-4">
    <div class="col-xl-5 mx-auto p-4">
        <!-- FORM ACTION? -->
        <form class="mb-4" asp-action="PrivateParticipant">
            <h4 style="color: var(--bg);">@ViewData["Title"]</h4>
            <partial name="_PrivateParticipantsPartial" model="Model" />
        </form>
    </div>
</div>

Events/Views/Shared/_CompanyParticipantsPartial.cshtml
@model Events.Models.EventsDetailsViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="EventsId" value="@Model.Events.Id" />
<div class="form-group row p-1">
    <label asp-for="companyParticipantsModel.Nimi" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.companyParticipantsModel.Nimi):</label>
    <div class="col-sm-8">
        <input asp-for="companyParticipantsModel.Nimi" class="form-control" />
        <span asp-validation-for="companyParticipantsModel.Nimi" class="text-danger"></span>
    </div>
</div>
<div class="form-group row p-1">
    <label asp-for="companyParticipantsModel.Registrikood" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.companyParticipantsModel.Registrikood):</label>
    <div class="col-sm-8">
        <input asp-for="companyParticipantsModel.Registrikood" class="form-control" />
        <span asp-validation-for="companyParticipantsModel.Registrikood" class="text-danger"></span>
    </div>
</div>
<div class="form-group row p-1">
    <label asp-for="companyParticipantsModel.Osavõtjate_arv" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.companyParticipantsModel.Osavõtjate_arv):</label>
    <div class="col-sm-8">
        <input asp-for="companyParticipantsModel.Osavõtjate_arv" class="form-control" />
        <span asp-validation-for="companyParticipantsModel.Osavõtjate_arv" class="text-danger"></span>
    </div>
</div>
<div class="form-group row p-1">
    <label asp-for="companyParticipantsModel.Maksmiseviis" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.companyParticipantsModel.Maksmiseviis):</label>
    <div class="col-sm-8">
        <select asp-for="companyParticipantsModel.Maksmiseviis" class="form-select">
            <option>Sularaha</option>
            <option>Pangaülekanne</option>
        </select>
        <span asp-validation-for="companyParticipantsModel.Maksmiseviis" class="text-danger"></span>
    </div>
</div>
<div class="form-group row p-1">
    <label asp-for="companyParticipantsModel.Lisainfo" class="col-lg-4 col-form-label">@Html.DisplayNameFor(model => model.companyParticipantsModel.Lisainfo):</label>
    <div class="col-sm-8">
        <textarea asp-for="companyParticipantsModel.Lisainfo" class="form-control"></textarea>
        <span asp-validation-for="companyParticipantsModel.Lisainfo" class="text-danger"></span>
    </div>
</div>
<div class="mt-5">
    <a onclick="history.back()" class="btn py-1 m-1" style="background-color: #e1e1e1;">Tagasi</a>
    <button type="submit" class="btn text-white py-1 m-1" style="background-color: var(--bg);">Salvesta</button>
</div>

Events/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Üritused</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Events.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container my-4">

        <!-- HEADER -->
        <header class="d-flex flex-wrap justify-content-center mb-4 px-5 bg-white">
            <img src="~/img/logo.svg" class="pe-5" alt="Logo" />
            <div class="d-flex px-5 mb-3 mb-md-0 me-md-auto text-uppercase fw-bold">
                <a class="p-4 nav-link text-dark" id="home" asp-area="" asp-controller="Home" asp-action="Index">Avaleht</a>
                <a class="p-4 nav-link text-dark" id="events" asp-area="" asp-controller="AddEvents" asp-action="Index">Ürituse lisamine</a>
            </div>
            <img src="~/img/symbol.svg" alt="Symbol" />
        </header>

        <main role="main">
            @RenderBody()
        </main>


        <!-- FOOTER -->
        <footer>
            <div class="row p-5 g-0 text-white">
                <div class="col">
                    <h2>Curabitur</h2>
                    <ul style="list-style-type:none; padding: 0" class="text-white-50">
                        <li>Emauris</li>
                        <li>Kfringla</li>
                        <li>Oin magna sem</li>
                        <li>Kelementum</li>
                    </ul>
                </div>
                <div class="col">
                    <h2>Fusce</h2>
                    <ul style="list-style-type:none; padding: 0" class="text-white-50">
                        <li>Econsectetur</li>
                        <li>Ksollicitudin</li>
                        <li>Omvulputate</li>
                        <li>Nunc fringilla tellu</li>
                    </ul>
                </div>
                <div class="col">
                    <h2>Kontakt</h2>
                    <ul style="list-style-type:none; padding: 0" class="text-white-50">
                        <li class="fw-bold">Peakontor: Tallinnas</li>
                        <li>Väike-Ameerika 1, 11415 Tallinn</li>
                        <li>Telefon: 605 4450</li>
                        <li>Faks: 605 3186</li>
                    </ul>
                </div>
                <div class="col pt-5">
                    <ul style="list-style-type:none; padding: 0" class="text-white-50">
                        <li class="fw-bold">Harukontor: Võrus</li>
                        <li>Oja tn 7 (külastusaadress)</li>
                        <li>Telefon: 605 3330</li>
                        <li>Faks: 605 3155</li>
                    </ul>
                </div>
            </div>
        </footer>

    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>